<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Suchtprophylaxe</title>



        <?php
        // echo $this->headLink()->appendStylesheet('/css/spl.css') 
//        echo $this->headLink()->appendStylesheet('/concept/full_screen_preview.css'); 
//        $this->headLink()->appendStylesheet('/concept/custom.css');
        $this->headLink()->appendStylesheet('/css/bootstrap.css');
        $this->headLink()->appendStylesheet('/css/spl.css');
        echo $this->headLink();
        
        ?>

        <?php echo $this->jQuery(); ?>

        <?php
        $this->headScript()->appendFile('/js/bootstrap/bootstrap.min.js');
        $this->headScript()->appendFile('/js/jquery/js/jquery-ui-1.10.4.custom.min.js');
        $this->headScript()->appendFile('/js/Menu.js');
        $this->headScript()->appendFile('/concept/jquery.transit.min.js');
//        $this->headScript()->appendFile('/concept/custom.js');
//
        echo $this->headScript();
        ?>


    </head>
    <body>

<!--        <a class="leftarrow"></a>
        
         <a class="rightarrow"></a>-->
       
        <div id="ontop">
            <div class="container">
                <div class="formRow">
                    <div class="top-info-wrapper">
                        <div id="logo" class="col-md-6">
<!--                            <a href="http://theme.concept7.vn/concept1">
                                <div class="logo-wrapper" style=""><img src="concept-Dateien/logo.png" alt="Concept 1"></div>                         
                            </a>-->
                        </div>
<!--                        <div class="col-md-6">
                            <h5>This theme is awesome. <a href="#" class="btn btn-nobg">Buy now</a></h5>
                        </div>-->

                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div id="nav-bar" class="wrapper">
            <div class="container">
                <div class="formRow">
                    <div class="">
                        <div class="navbar ">
                            <div class="navbar-inner">

                                <div class="nav-collapse">
                                    <?php
                                    $this->navigation()->menu()->setPartial('menu.phtml'); // RICHTIGE
                                    echo $this->navigation();
                                    ?> 
                                </div>

                                <!--                                <form id="searchbar" class="navbar-search pull-right" action="http://theme.concept7.vn/concept1/" method="get">
                                                                    <input name="s" class="search-query" value="Search" type="text">
                                                                        <i class="icon-search"></i>
                                                                </form>-->

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->layout()->content ?>

        <div id="footer" class="navbar-fixed-bottom">
            <div class="container">     
                <div class="navbar">
                    <?php
                    echo $this->navigation()->menu()->renderMenu($this->footer, array('ulClass' => 'nav'));
                    ?>
                </div>
            </div>
        </div>
    </body>
</html>