<div class="col-md-12 ">
    <div>

    </div>

    <div>
        <ul>
            <li>
                punkt 1
            </li>        
            <li>
                punkt 2
            </li>
        </ul>
    </div>

    <table id="maxim_table" border="">
        <thead>
            <tr>
                <th>ID</th>
                <th>Text</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

</div>